python .\scripts\gate_suite.py `
  --kind feverous `
  --in_path .\datasets\feverous\feverous_dev_challenges.jsonl `
  --top_k 10 --seed 1337 `
  --cal_frac 0.5 `
  --far 0.01 `
  --neg_mode deranged `
  --out_report .\artifacts\feverous_negcal.json `
  --out_pos_scored .\artifacts\feverous_scored_pos.jsonl `
  --out_neg_scored .\artifacts\feverous_scored_neg.jsonl `
  --out_plot .\artifacts\feverous_sep.png
