python .\scripts\gate_suite.py `
  --kind jsonl `
  --in_path .\datasets\scifact\scifact_dev_rationale.jsonl `
  --n 500 --seed 1337 `
  --cal_frac 0.5 `
  --far 0.01 `
  --neg_mode deranged `
  --out_report .\artifacts\scifact_negcal.json `
  --out_pos_scored .\artifacts\scifact_scored_pos.jsonl `
  --out_neg_scored .\artifacts\scifact_scored_neg.jsonl `
  --plot_png .\artifacts\scifact_sep.png
